// <auto-generated />
using System;
using Beautique.DataAcess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Beautique.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250514200100_AddReview")]
    partial class AddReview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Beautique.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Shampoos & Conditioners"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Body Washes & Soaps"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Facial Care"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 4,
                            Name = "Body Care"
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 5,
                            Name = "Deodorants & Antiperspirants"
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 6,
                            Name = "Shaving Products"
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 7,
                            Name = "Nail Care"
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 8,
                            Name = "Perfumes & Fragrances"
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 9,
                            Name = "Lip Care"
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 10,
                            Name = "Hand Care"
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 11,
                            Name = "Hair Care"
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 12,
                            Name = "Eye & Eyelid Care"
                        },
                        new
                        {
                            Id = 13,
                            DisplayOrder = 13,
                            Name = "Cleansing & Makeup Removal"
                        },
                        new
                        {
                            Id = 14,
                            DisplayOrder = 14,
                            Name = "Organic & Bio Cosmetics"
                        });
                });

            modelBuilder.Entity("Beautique.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "SkinCare City",
                            Name = "Glow & Care",
                            PhoneNumber = "5557778888",
                            PostalCode = "54321",
                            State = "CA",
                            StreetAddress = "123 Beauty Ave"
                        },
                        new
                        {
                            Id = 2,
                            City = "GreenVille",
                            Name = "Nature's Touch",
                            PhoneNumber = "4446669999",
                            PostalCode = "67890",
                            State = "OR",
                            StreetAddress = "456 Herbal Rd"
                        },
                        new
                        {
                            Id = 3,
                            City = "Shampoo Town",
                            Name = "Silky Locks",
                            PhoneNumber = "3335557777",
                            PostalCode = "11223",
                            State = "TX",
                            StreetAddress = "789 Hair Blvd"
                        });
                });

            modelBuilder.Entity("Beautique.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Beautique.Models.OrderHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OrderTotal")
                        .HasColumnType("float");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("PaymentDueDate")
                        .HasColumnType("date");

                    b.Property<string>("PaymentIntentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ShippingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("Beautique.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BarCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<string>("Maker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price50")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BarCode = "SW123456789",
                            CategoryId = 1,
                            Description = "A premium shampoo that provides ultimate shine and smoothness.",
                            ImageUrl = "",
                            ListPrice = 55.0,
                            Maker = "SparkLife",
                            Price = 50.0,
                            Price100 = 40.0,
                            Price50 = 45.0,
                            Title = "ShineWave"
                        },
                        new
                        {
                            Id = 2,
                            BarCode = "PG987654321",
                            CategoryId = 2,
                            Description = "A gentle body wash that leaves your skin refreshed and hydrated.",
                            ImageUrl = "",
                            ListPrice = 40.0,
                            Maker = "CleanseCo",
                            Price = 35.0,
                            Price100 = 25.0,
                            Price50 = 30.0,
                            Title = "PureGlow"
                        },
                        new
                        {
                            Id = 3,
                            BarCode = "ST111223344",
                            CategoryId = 3,
                            Description = "A soft and nourishing facial cream for smooth and glowing skin.",
                            ImageUrl = "",
                            ListPrice = 65.0,
                            Maker = "VelvetSkin",
                            Price = 60.0,
                            Price100 = 50.0,
                            Price50 = 55.0,
                            Title = "SoftTouch"
                        },
                        new
                        {
                            Id = 4,
                            BarCode = "CS554433221",
                            CategoryId = 5,
                            Description = "A refreshing deodorant spray that keeps you fresh all day long.",
                            ImageUrl = "",
                            ListPrice = 20.0,
                            Maker = "LushCare",
                            Price = 18.0,
                            Price100 = 14.0,
                            Price50 = 16.0,
                            Title = "ClearSpark"
                        },
                        new
                        {
                            Id = 5,
                            BarCode = "FC998877665",
                            CategoryId = 6,
                            Description = "A shaving gel that provides a smooth and irritation-free shave.",
                            ImageUrl = "",
                            ListPrice = 35.0,
                            Maker = "SharpEdge",
                            Price = 30.0,
                            Price100 = 25.0,
                            Price50 = 28.0,
                            Title = "FreshCut"
                        },
                        new
                        {
                            Id = 6,
                            BarCode = "GN332211445",
                            CategoryId = 7,
                            Description = "A long-lasting nail polish with vibrant colors and a glossy finish.",
                            ImageUrl = "",
                            ListPrice = 15.0,
                            Maker = "NailArt",
                            Price = 13.0,
                            Price100 = 10.0,
                            Price50 = 12.0,
                            Title = "GlowNail"
                        },
                        new
                        {
                            Id = 7,
                            BarCode = "EV776655443",
                            CategoryId = 8,
                            Description = "A fresh and uplifting fragrance that is perfect for daily wear.",
                            ImageUrl = "",
                            ListPrice = 50.0,
                            Maker = "ScentAura",
                            Price = 45.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "EauVibe"
                        },
                        new
                        {
                            Id = 8,
                            BarCode = "SK223344556",
                            CategoryId = 9,
                            Description = "A hydrating lip balm with a smooth texture and subtle scent.",
                            ImageUrl = "",
                            ListPrice = 10.0,
                            Maker = "LipsCare",
                            Price = 9.0,
                            Price100 = 7.0,
                            Price50 = 8.0,
                            Title = "SoftKiss"
                        },
                        new
                        {
                            Id = 9,
                            BarCode = "HH556677889",
                            CategoryId = 10,
                            Description = "A nourishing hand cream that keeps your skin soft and hydrated.",
                            ImageUrl = "",
                            ListPrice = 18.0,
                            Maker = "SkinGuard",
                            Price = 16.0,
                            Price100 = 12.0,
                            Price50 = 14.0,
                            Title = "HandHeal"
                        },
                        new
                        {
                            Id = 10,
                            BarCode = "EL998877665",
                            CategoryId = 12,
                            Description = "A rejuvenating eye cream that targets puffiness and dark circles.",
                            ImageUrl = "",
                            ListPrice = 45.0,
                            Maker = "VisionGlow",
                            Price = 40.0,
                            Price100 = 30.0,
                            Price50 = 35.0,
                            Title = "EyeLuxe"
                        },
                        new
                        {
                            Id = 11,
                            BarCode = "BC000000011",
                            CategoryId = 11,
                            Description = "A nourishing oil for damaged hair.",
                            ImageUrl = "",
                            ListPrice = 33.0,
                            Maker = "GlowHair",
                            Price = 28.0,
                            Price100 = 18.0,
                            Price50 = 23.0,
                            Title = "ShineElixir"
                        },
                        new
                        {
                            Id = 12,
                            BarCode = "BC000000012",
                            CategoryId = 12,
                            Description = "Targets dark circles and fine lines.",
                            ImageUrl = "",
                            ListPrice = 58.0,
                            Maker = "BrightEyes",
                            Price = 53.0,
                            Price100 = 43.0,
                            Price50 = 48.0,
                            Title = "CalmBright"
                        },
                        new
                        {
                            Id = 13,
                            BarCode = "BC000000013",
                            CategoryId = 13,
                            Description = "A gentle remover for all makeup types.",
                            ImageUrl = "",
                            ListPrice = 50.0,
                            Maker = "CleanSwipe",
                            Price = 45.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "MicellarWipe"
                        },
                        new
                        {
                            Id = 14,
                            BarCode = "BC000000014",
                            CategoryId = 14,
                            Description = "An organic skin lotion with no parabens.",
                            ImageUrl = "",
                            ListPrice = 45.0,
                            Maker = "BioCare",
                            Price = 40.0,
                            Price100 = 30.0,
                            Price50 = 35.0,
                            Title = "BioVital"
                        },
                        new
                        {
                            Id = 15,
                            BarCode = "BC000000015",
                            CategoryId = 1,
                            Description = "A revitalizing shampoo for daily use.",
                            ImageUrl = "",
                            ListPrice = 20.0,
                            Maker = "ShinyLocks",
                            Price = 15.0,
                            Price100 = 5.0,
                            Price50 = 10.0,
                            Title = "HydraBounce"
                        },
                        new
                        {
                            Id = 16,
                            BarCode = "BC000000016",
                            CategoryId = 2,
                            Description = "A moisturizing body wash with essential oils.",
                            ImageUrl = "",
                            ListPrice = 36.0,
                            Maker = "AquaFresh",
                            Price = 31.0,
                            Price100 = 21.0,
                            Price50 = 26.0,
                            Title = "ZenAqua"
                        },
                        new
                        {
                            Id = 17,
                            BarCode = "BC000000017",
                            CategoryId = 3,
                            Description = "A facial cream enriched with vitamins.",
                            ImageUrl = "",
                            ListPrice = 23.0,
                            Maker = "DermaGlow",
                            Price = 18.0,
                            Price100 = 8.0,
                            Price50 = 13.0,
                            Title = "ToneCare"
                        },
                        new
                        {
                            Id = 18,
                            BarCode = "BC000000018",
                            CategoryId = 4,
                            Description = "A hydrating lotion for silky skin.",
                            ImageUrl = "",
                            ListPrice = 41.0,
                            Maker = "SmoothCare",
                            Price = 36.0,
                            Price100 = 26.0,
                            Price50 = 31.0,
                            Title = "SmoothHydra"
                        },
                        new
                        {
                            Id = 19,
                            BarCode = "BC000000019",
                            CategoryId = 5,
                            Description = "A long-lasting deodorant for active days.",
                            ImageUrl = "",
                            ListPrice = 55.0,
                            Maker = "FreshShield",
                            Price = 50.0,
                            Price100 = 40.0,
                            Price50 = 45.0,
                            Title = "BlockActive"
                        },
                        new
                        {
                            Id = 20,
                            BarCode = "BC000000020",
                            CategoryId = 6,
                            Description = "A rich shaving cream for sensitive skin.",
                            ImageUrl = "",
                            ListPrice = 27.0,
                            Maker = "BladeGuard",
                            Price = 22.0,
                            Price100 = 12.0,
                            Price50 = 17.0,
                            Title = "BladeSmooth"
                        },
                        new
                        {
                            Id = 21,
                            BarCode = "BC000000021",
                            CategoryId = 7,
                            Description = "Bright nail polish with lasting power.",
                            ImageUrl = "",
                            ListPrice = 60.0,
                            Maker = "ColorShine",
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "TintSparkle"
                        },
                        new
                        {
                            Id = 22,
                            BarCode = "BC000000022",
                            CategoryId = 8,
                            Description = "A light perfume with floral notes.",
                            ImageUrl = "",
                            ListPrice = 54.0,
                            Maker = "EssenceMist",
                            Price = 49.0,
                            Price100 = 39.0,
                            Price50 = 44.0,
                            Title = "AuraMist"
                        },
                        new
                        {
                            Id = 23,
                            BarCode = "BC000000023",
                            CategoryId = 9,
                            Description = "A soothing balm for chapped lips.",
                            ImageUrl = "",
                            ListPrice = 58.0,
                            Maker = "LipSilk",
                            Price = 53.0,
                            Price100 = 43.0,
                            Price50 = 48.0,
                            Title = "SilkSoft"
                        },
                        new
                        {
                            Id = 24,
                            BarCode = "BC000000024",
                            CategoryId = 10,
                            Description = "A cream to restore dry hands.",
                            ImageUrl = "",
                            ListPrice = 47.0,
                            Maker = "PalmSoft",
                            Price = 42.0,
                            Price100 = 32.0,
                            Price50 = 37.0,
                            Title = "HealCare"
                        },
                        new
                        {
                            Id = 25,
                            BarCode = "BC000000025",
                            CategoryId = 11,
                            Description = "A nourishing oil for damaged hair.",
                            ImageUrl = "",
                            ListPrice = 58.0,
                            Maker = "GlowHair",
                            Price = 53.0,
                            Price100 = 43.0,
                            Price50 = 48.0,
                            Title = "NourishSilk"
                        },
                        new
                        {
                            Id = 26,
                            BarCode = "BC000000026",
                            CategoryId = 12,
                            Description = "Targets dark circles and fine lines.",
                            ImageUrl = "",
                            ListPrice = 50.0,
                            Maker = "BrightEyes",
                            Price = 45.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "FreshEye"
                        },
                        new
                        {
                            Id = 27,
                            BarCode = "BC000000027",
                            CategoryId = 13,
                            Description = "A gentle remover for all makeup types.",
                            ImageUrl = "",
                            ListPrice = 57.0,
                            Maker = "CleanSwipe",
                            Price = 52.0,
                            Price100 = 42.0,
                            Price50 = 47.0,
                            Title = "WashMicellar"
                        },
                        new
                        {
                            Id = 28,
                            BarCode = "BC000000028",
                            CategoryId = 14,
                            Description = "An organic skin lotion with no parabens.",
                            ImageUrl = "",
                            ListPrice = 53.0,
                            Maker = "BioCare",
                            Price = 48.0,
                            Price100 = 38.0,
                            Price50 = 43.0,
                            Title = "HerbalOrganic"
                        },
                        new
                        {
                            Id = 29,
                            BarCode = "BC000000029",
                            CategoryId = 1,
                            Description = "A revitalizing shampoo for daily use.",
                            ImageUrl = "",
                            ListPrice = 61.0,
                            Maker = "ShinyLocks",
                            Price = 56.0,
                            Price100 = 46.0,
                            Price50 = 51.0,
                            Title = "SmoothGlow"
                        },
                        new
                        {
                            Id = 30,
                            BarCode = "BC000000030",
                            CategoryId = 2,
                            Description = "A moisturizing body wash with essential oils.",
                            ImageUrl = "",
                            ListPrice = 36.0,
                            Maker = "AquaFresh",
                            Price = 31.0,
                            Price100 = 21.0,
                            Price50 = 26.0,
                            Title = "PureCleanse"
                        },
                        new
                        {
                            Id = 31,
                            BarCode = "BC000000031",
                            CategoryId = 3,
                            Description = "A facial cream enriched with vitamins.",
                            ImageUrl = "",
                            ListPrice = 25.0,
                            Maker = "DermaGlow",
                            Price = 20.0,
                            Price100 = 10.0,
                            Price50 = 15.0,
                            Title = "ToneBalance"
                        },
                        new
                        {
                            Id = 32,
                            BarCode = "BC000000032",
                            CategoryId = 4,
                            Description = "A hydrating lotion for silky skin.",
                            ImageUrl = "",
                            ListPrice = 61.0,
                            Maker = "SmoothCare",
                            Price = 56.0,
                            Price100 = 46.0,
                            Price50 = 51.0,
                            Title = "HydraSilk"
                        },
                        new
                        {
                            Id = 33,
                            BarCode = "BC000000033",
                            CategoryId = 5,
                            Description = "A long-lasting deodorant for active days.",
                            ImageUrl = "",
                            ListPrice = 43.0,
                            Maker = "FreshShield",
                            Price = 38.0,
                            Price100 = 28.0,
                            Price50 = 33.0,
                            Title = "BlockPower"
                        },
                        new
                        {
                            Id = 34,
                            BarCode = "BC000000034",
                            CategoryId = 6,
                            Description = "A rich shaving cream for sensitive skin.",
                            ImageUrl = "",
                            ListPrice = 49.0,
                            Maker = "BladeGuard",
                            Price = 44.0,
                            Price100 = 34.0,
                            Price50 = 39.0,
                            Title = "FreshCalm"
                        },
                        new
                        {
                            Id = 35,
                            BarCode = "BC000000035",
                            CategoryId = 7,
                            Description = "Bright nail polish with lasting power.",
                            ImageUrl = "",
                            ListPrice = 23.0,
                            Maker = "ColorShine",
                            Price = 18.0,
                            Price100 = 8.0,
                            Price50 = 13.0,
                            Title = "PopTint"
                        },
                        new
                        {
                            Id = 36,
                            BarCode = "BC000000036",
                            CategoryId = 8,
                            Description = "A light perfume with floral notes.",
                            ImageUrl = "",
                            ListPrice = 31.0,
                            Maker = "EssenceMist",
                            Price = 26.0,
                            Price100 = 16.0,
                            Price50 = 21.0,
                            Title = "MistDream"
                        },
                        new
                        {
                            Id = 37,
                            BarCode = "BC000000037",
                            CategoryId = 9,
                            Description = "A soothing balm for chapped lips.",
                            ImageUrl = "",
                            ListPrice = 42.0,
                            Maker = "LipSilk",
                            Price = 37.0,
                            Price100 = 27.0,
                            Price50 = 32.0,
                            Title = "SilkSmooth"
                        },
                        new
                        {
                            Id = 38,
                            BarCode = "BC000000038",
                            CategoryId = 10,
                            Description = "A cream to restore dry hands.",
                            ImageUrl = "",
                            ListPrice = 25.0,
                            Maker = "PalmSoft",
                            Price = 20.0,
                            Price100 = 10.0,
                            Price50 = 15.0,
                            Title = "CalmShield"
                        },
                        new
                        {
                            Id = 39,
                            BarCode = "BC000000039",
                            CategoryId = 11,
                            Description = "A nourishing oil for damaged hair.",
                            ImageUrl = "",
                            ListPrice = 56.0,
                            Maker = "GlowHair",
                            Price = 51.0,
                            Price100 = 41.0,
                            Price50 = 46.0,
                            Title = "ShineCare"
                        },
                        new
                        {
                            Id = 40,
                            BarCode = "BC000000040",
                            CategoryId = 12,
                            Description = "Targets dark circles and fine lines.",
                            ImageUrl = "",
                            ListPrice = 54.0,
                            Maker = "BrightEyes",
                            Price = 49.0,
                            Price100 = 39.0,
                            Price50 = 44.0,
                            Title = "LuxeEye"
                        },
                        new
                        {
                            Id = 41,
                            BarCode = "BC000000041",
                            CategoryId = 13,
                            Description = "A gentle remover for all makeup types.",
                            ImageUrl = "",
                            ListPrice = 53.0,
                            Maker = "CleanSwipe",
                            Price = 48.0,
                            Price100 = 38.0,
                            Price50 = 43.0,
                            Title = "FoamWash"
                        },
                        new
                        {
                            Id = 42,
                            BarCode = "BC000000042",
                            CategoryId = 14,
                            Description = "An organic skin lotion with no parabens.",
                            ImageUrl = "",
                            ListPrice = 58.0,
                            Maker = "BioCare",
                            Price = 53.0,
                            Price100 = 43.0,
                            Price50 = 48.0,
                            Title = "BioOrganic"
                        },
                        new
                        {
                            Id = 43,
                            BarCode = "BC000000043",
                            CategoryId = 1,
                            Description = "A revitalizing shampoo for daily use.",
                            ImageUrl = "",
                            ListPrice = 60.0,
                            Maker = "ShinyLocks",
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "SilkBounce"
                        },
                        new
                        {
                            Id = 44,
                            BarCode = "BC000000044",
                            CategoryId = 2,
                            Description = "A moisturizing body wash with essential oils.",
                            ImageUrl = "",
                            ListPrice = 51.0,
                            Maker = "AquaFresh",
                            Price = 46.0,
                            Price100 = 36.0,
                            Price50 = 41.0,
                            Title = "PureBloom"
                        },
                        new
                        {
                            Id = 45,
                            BarCode = "BC000000045",
                            CategoryId = 3,
                            Description = "A facial cream enriched with vitamins.",
                            ImageUrl = "",
                            ListPrice = 30.0,
                            Maker = "DermaGlow",
                            Price = 25.0,
                            Price100 = 15.0,
                            Price50 = 20.0,
                            Title = "FreshBalance"
                        },
                        new
                        {
                            Id = 46,
                            BarCode = "BC000000046",
                            CategoryId = 4,
                            Description = "A hydrating lotion for silky skin.",
                            ImageUrl = "",
                            ListPrice = 35.0,
                            Maker = "SmoothCare",
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "TouchSmooth"
                        },
                        new
                        {
                            Id = 47,
                            BarCode = "BC000000047",
                            CategoryId = 5,
                            Description = "A long-lasting deodorant for active days.",
                            ImageUrl = "",
                            ListPrice = 27.0,
                            Maker = "FreshShield",
                            Price = 22.0,
                            Price100 = 12.0,
                            Price50 = 17.0,
                            Title = "GuardZone"
                        },
                        new
                        {
                            Id = 48,
                            BarCode = "BC000000048",
                            CategoryId = 6,
                            Description = "A rich shaving cream for sensitive skin.",
                            ImageUrl = "",
                            ListPrice = 51.0,
                            Maker = "BladeGuard",
                            Price = 46.0,
                            Price100 = 36.0,
                            Price50 = 41.0,
                            Title = "FoamSmooth"
                        },
                        new
                        {
                            Id = 49,
                            BarCode = "BC000000049",
                            CategoryId = 7,
                            Description = "Bright nail polish with lasting power.",
                            ImageUrl = "",
                            ListPrice = 65.0,
                            Maker = "ColorShine",
                            Price = 60.0,
                            Price100 = 50.0,
                            Price50 = 55.0,
                            Title = "TintGlam"
                        },
                        new
                        {
                            Id = 50,
                            BarCode = "BC000000050",
                            CategoryId = 8,
                            Description = "A light perfume with floral notes.",
                            ImageUrl = "",
                            ListPrice = 27.0,
                            Maker = "EssenceMist",
                            Price = 22.0,
                            Price100 = 12.0,
                            Price50 = 17.0,
                            Title = "DreamBloom"
                        },
                        new
                        {
                            Id = 51,
                            BarCode = "BC000000051",
                            CategoryId = 9,
                            Description = "A soothing balm for chapped lips.",
                            ImageUrl = "",
                            ListPrice = 51.0,
                            Maker = "LipSilk",
                            Price = 46.0,
                            Price100 = 36.0,
                            Price50 = 41.0,
                            Title = "SoftSilk"
                        },
                        new
                        {
                            Id = 52,
                            BarCode = "BC000000052",
                            CategoryId = 10,
                            Description = "A cream to restore dry hands.",
                            ImageUrl = "",
                            ListPrice = 54.0,
                            Maker = "PalmSoft",
                            Price = 49.0,
                            Price100 = 39.0,
                            Price50 = 44.0,
                            Title = "RepairCalm"
                        },
                        new
                        {
                            Id = 53,
                            BarCode = "BC000000053",
                            CategoryId = 11,
                            Description = "A nourishing oil for damaged hair.",
                            ImageUrl = "",
                            ListPrice = 42.0,
                            Maker = "GlowHair",
                            Price = 37.0,
                            Price100 = 27.0,
                            Price50 = 32.0,
                            Title = "OilCare"
                        },
                        new
                        {
                            Id = 54,
                            BarCode = "BC000000054",
                            CategoryId = 12,
                            Description = "Targets dark circles and fine lines.",
                            ImageUrl = "",
                            ListPrice = 23.0,
                            Maker = "BrightEyes",
                            Price = 18.0,
                            Price100 = 8.0,
                            Price50 = 13.0,
                            Title = "CalmLuxe"
                        },
                        new
                        {
                            Id = 55,
                            BarCode = "BC000000055",
                            CategoryId = 13,
                            Description = "A gentle remover for all makeup types.",
                            ImageUrl = "",
                            ListPrice = 54.0,
                            Maker = "CleanSwipe",
                            Price = 49.0,
                            Price100 = 39.0,
                            Price50 = 44.0,
                            Title = "MicellarClean"
                        },
                        new
                        {
                            Id = 56,
                            BarCode = "BC000000056",
                            CategoryId = 14,
                            Description = "An organic skin lotion with no parabens.",
                            ImageUrl = "",
                            ListPrice = 52.0,
                            Maker = "BioCare",
                            Price = 47.0,
                            Price100 = 37.0,
                            Price50 = 42.0,
                            Title = "NatureGreen"
                        },
                        new
                        {
                            Id = 57,
                            BarCode = "BC000000057",
                            CategoryId = 1,
                            Description = "A revitalizing shampoo for daily use.",
                            ImageUrl = "",
                            ListPrice = 62.0,
                            Maker = "ShinyLocks",
                            Price = 57.0,
                            Price100 = 47.0,
                            Price50 = 52.0,
                            Title = "ShineSilk"
                        },
                        new
                        {
                            Id = 58,
                            BarCode = "BC000000058",
                            CategoryId = 2,
                            Description = "A moisturizing body wash with essential oils.",
                            ImageUrl = "",
                            ListPrice = 17.0,
                            Maker = "AquaFresh",
                            Price = 12.0,
                            Price100 = 2.0,
                            Price50 = 7.0,
                            Title = "BloomFoam"
                        },
                        new
                        {
                            Id = 59,
                            BarCode = "BC000000059",
                            CategoryId = 3,
                            Description = "A facial cream enriched with vitamins.",
                            ImageUrl = "",
                            ListPrice = 47.0,
                            Maker = "DermaGlow",
                            Price = 42.0,
                            Price100 = 32.0,
                            Price50 = 37.0,
                            Title = "VelvetGlow"
                        },
                        new
                        {
                            Id = 60,
                            BarCode = "BC000000060",
                            CategoryId = 4,
                            Description = "A hydrating lotion for silky skin.",
                            ImageUrl = "",
                            ListPrice = 53.0,
                            Maker = "SmoothCare",
                            Price = 48.0,
                            Price100 = 38.0,
                            Price50 = 43.0,
                            Title = "ButterSilk"
                        },
                        new
                        {
                            Id = 61,
                            BarCode = "BC000000061",
                            CategoryId = 5,
                            Description = "A long-lasting deodorant for active days.",
                            ImageUrl = "",
                            ListPrice = 43.0,
                            Maker = "FreshShield",
                            Price = 38.0,
                            Price100 = 28.0,
                            Price50 = 33.0,
                            Title = "FreshShield"
                        },
                        new
                        {
                            Id = 62,
                            BarCode = "BC000000062",
                            CategoryId = 6,
                            Description = "A rich shaving cream for sensitive skin.",
                            ImageUrl = "",
                            ListPrice = 53.0,
                            Maker = "BladeGuard",
                            Price = 48.0,
                            Price100 = 38.0,
                            Price50 = 43.0,
                            Title = "SmoothCalm"
                        },
                        new
                        {
                            Id = 63,
                            BarCode = "BC000000063",
                            CategoryId = 7,
                            Description = "Bright nail polish with lasting power.",
                            ImageUrl = "",
                            ListPrice = 42.0,
                            Maker = "ColorShine",
                            Price = 37.0,
                            Price100 = 27.0,
                            Price50 = 32.0,
                            Title = "GlamTint"
                        },
                        new
                        {
                            Id = 64,
                            BarCode = "BC000000064",
                            CategoryId = 8,
                            Description = "A light perfume with floral notes.",
                            ImageUrl = "",
                            ListPrice = 62.0,
                            Maker = "EssenceMist",
                            Price = 57.0,
                            Price100 = 47.0,
                            Price50 = 52.0,
                            Title = "EssenceAura"
                        },
                        new
                        {
                            Id = 65,
                            BarCode = "BC000000065",
                            CategoryId = 9,
                            Description = "A soothing balm for chapped lips.",
                            ImageUrl = "",
                            ListPrice = 30.0,
                            Maker = "LipSilk",
                            Price = 25.0,
                            Price100 = 15.0,
                            Price50 = 20.0,
                            Title = "GlowSilk"
                        },
                        new
                        {
                            Id = 66,
                            BarCode = "BC000000066",
                            CategoryId = 10,
                            Description = "A cream to restore dry hands.",
                            ImageUrl = "",
                            ListPrice = 19.0,
                            Maker = "PalmSoft",
                            Price = 14.0,
                            Price100 = 4.0,
                            Price50 = 9.0,
                            Title = "CareGuard"
                        },
                        new
                        {
                            Id = 67,
                            BarCode = "BC000000067",
                            CategoryId = 11,
                            Description = "A nourishing oil for damaged hair.",
                            ImageUrl = "",
                            ListPrice = 19.0,
                            Maker = "GlowHair",
                            Price = 14.0,
                            Price100 = 4.0,
                            Price50 = 9.0,
                            Title = "ElixirSilk"
                        },
                        new
                        {
                            Id = 68,
                            BarCode = "BC000000068",
                            CategoryId = 12,
                            Description = "Targets dark circles and fine lines.",
                            ImageUrl = "",
                            ListPrice = 21.0,
                            Maker = "BrightEyes",
                            Price = 16.0,
                            Price100 = 6.0,
                            Price50 = 11.0,
                            Title = "GlowBright"
                        },
                        new
                        {
                            Id = 69,
                            BarCode = "BC000000069",
                            CategoryId = 13,
                            Description = "A gentle remover for all makeup types.",
                            ImageUrl = "",
                            ListPrice = 48.0,
                            Maker = "CleanSwipe",
                            Price = 43.0,
                            Price100 = 33.0,
                            Price50 = 38.0,
                            Title = "WashFoam"
                        },
                        new
                        {
                            Id = 70,
                            BarCode = "BC000000070",
                            CategoryId = 14,
                            Description = "An organic skin lotion with no parabens.",
                            ImageUrl = "",
                            ListPrice = 23.0,
                            Maker = "BioCare",
                            Price = 18.0,
                            Price100 = 8.0,
                            Price50 = 13.0,
                            Title = "PureBio"
                        },
                        new
                        {
                            Id = 71,
                            BarCode = "BC000000071",
                            CategoryId = 1,
                            Description = "A revitalizing shampoo for daily use.",
                            ImageUrl = "",
                            ListPrice = 30.0,
                            Maker = "ShinyLocks",
                            Price = 25.0,
                            Price100 = 15.0,
                            Price50 = 20.0,
                            Title = "LusterHydra"
                        },
                        new
                        {
                            Id = 72,
                            BarCode = "BC000000072",
                            CategoryId = 2,
                            Description = "A moisturizing body wash with essential oils.",
                            ImageUrl = "",
                            ListPrice = 46.0,
                            Maker = "AquaFresh",
                            Price = 41.0,
                            Price100 = 31.0,
                            Price50 = 36.0,
                            Title = "BloomWave"
                        },
                        new
                        {
                            Id = 73,
                            BarCode = "BC000000073",
                            CategoryId = 3,
                            Description = "A facial cream enriched with vitamins.",
                            ImageUrl = "",
                            ListPrice = 35.0,
                            Maker = "DermaGlow",
                            Price = 30.0,
                            Price100 = 20.0,
                            Price50 = 25.0,
                            Title = "VelvetTone"
                        },
                        new
                        {
                            Id = 74,
                            BarCode = "BC000000074",
                            CategoryId = 4,
                            Description = "A hydrating lotion for silky skin.",
                            ImageUrl = "",
                            ListPrice = 25.0,
                            Maker = "SmoothCare",
                            Price = 20.0,
                            Price100 = 10.0,
                            Price50 = 15.0,
                            Title = "TouchSilk"
                        },
                        new
                        {
                            Id = 75,
                            BarCode = "BC000000075",
                            CategoryId = 5,
                            Description = "A long-lasting deodorant for active days.",
                            ImageUrl = "",
                            ListPrice = 16.0,
                            Maker = "FreshShield",
                            Price = 11.0,
                            Price100 = 1.0,
                            Price50 = 6.0,
                            Title = "GuardPower"
                        },
                        new
                        {
                            Id = 76,
                            BarCode = "BC000000076",
                            CategoryId = 6,
                            Description = "A rich shaving cream for sensitive skin.",
                            ImageUrl = "",
                            ListPrice = 52.0,
                            Maker = "BladeGuard",
                            Price = 47.0,
                            Price100 = 37.0,
                            Price50 = 42.0,
                            Title = "EdgeFoam"
                        },
                        new
                        {
                            Id = 77,
                            BarCode = "BC000000077",
                            CategoryId = 7,
                            Description = "Bright nail polish with lasting power.",
                            ImageUrl = "",
                            ListPrice = 27.0,
                            Maker = "ColorShine",
                            Price = 22.0,
                            Price100 = 12.0,
                            Price50 = 17.0,
                            Title = "TintGloss"
                        },
                        new
                        {
                            Id = 78,
                            BarCode = "BC000000078",
                            CategoryId = 8,
                            Description = "A light perfume with floral notes.",
                            ImageUrl = "",
                            ListPrice = 59.0,
                            Maker = "EssenceMist",
                            Price = 54.0,
                            Price100 = 44.0,
                            Price50 = 49.0,
                            Title = "ScentBloom"
                        },
                        new
                        {
                            Id = 79,
                            BarCode = "BC000000079",
                            CategoryId = 9,
                            Description = "A soothing balm for chapped lips.",
                            ImageUrl = "",
                            ListPrice = 22.0,
                            Maker = "LipSilk",
                            Price = 17.0,
                            Price100 = 7.0,
                            Price50 = 12.0,
                            Title = "HydraGlow"
                        },
                        new
                        {
                            Id = 80,
                            BarCode = "BC000000080",
                            CategoryId = 10,
                            Description = "A cream to restore dry hands.",
                            ImageUrl = "",
                            ListPrice = 17.0,
                            Maker = "PalmSoft",
                            Price = 12.0,
                            Price100 = 2.0,
                            Price50 = 7.0,
                            Title = "VelvetSoft"
                        },
                        new
                        {
                            Id = 81,
                            BarCode = "BC000000081",
                            CategoryId = 11,
                            Description = "A nourishing oil for damaged hair.",
                            ImageUrl = "",
                            ListPrice = 47.0,
                            Maker = "GlowHair",
                            Price = 42.0,
                            Price100 = 32.0,
                            Price50 = 37.0,
                            Title = "OilSilk"
                        },
                        new
                        {
                            Id = 82,
                            BarCode = "BC000000082",
                            CategoryId = 12,
                            Description = "Targets dark circles and fine lines.",
                            ImageUrl = "",
                            ListPrice = 42.0,
                            Maker = "BrightEyes",
                            Price = 37.0,
                            Price100 = 27.0,
                            Price50 = 32.0,
                            Title = "CalmLift"
                        },
                        new
                        {
                            Id = 83,
                            BarCode = "BC000000083",
                            CategoryId = 13,
                            Description = "A gentle remover for all makeup types.",
                            ImageUrl = "",
                            ListPrice = 16.0,
                            Maker = "CleanSwipe",
                            Price = 11.0,
                            Price100 = 1.0,
                            Price50 = 6.0,
                            Title = "CleanMicellar"
                        },
                        new
                        {
                            Id = 84,
                            BarCode = "BC000000084",
                            CategoryId = 14,
                            Description = "An organic skin lotion with no parabens.",
                            ImageUrl = "",
                            ListPrice = 49.0,
                            Maker = "BioCare",
                            Price = 44.0,
                            Price100 = 34.0,
                            Price50 = 39.0,
                            Title = "OrganicBio"
                        },
                        new
                        {
                            Id = 85,
                            BarCode = "BC000000085",
                            CategoryId = 1,
                            Description = "A revitalizing shampoo for daily use.",
                            ImageUrl = "",
                            ListPrice = 62.0,
                            Maker = "ShinyLocks",
                            Price = 57.0,
                            Price100 = 47.0,
                            Price50 = 52.0,
                            Title = "FreshSilk"
                        },
                        new
                        {
                            Id = 86,
                            BarCode = "BC000000086",
                            CategoryId = 2,
                            Description = "A moisturizing body wash with essential oils.",
                            ImageUrl = "",
                            ListPrice = 49.0,
                            Maker = "AquaFresh",
                            Price = 44.0,
                            Price100 = 34.0,
                            Price50 = 39.0,
                            Title = "CleanseMist"
                        },
                        new
                        {
                            Id = 87,
                            BarCode = "BC000000087",
                            CategoryId = 3,
                            Description = "A facial cream enriched with vitamins.",
                            ImageUrl = "",
                            ListPrice = 37.0,
                            Maker = "DermaGlow",
                            Price = 32.0,
                            Price100 = 22.0,
                            Price50 = 27.0,
                            Title = "FreshSoft"
                        },
                        new
                        {
                            Id = 88,
                            BarCode = "BC000000088",
                            CategoryId = 4,
                            Description = "A hydrating lotion for silky skin.",
                            ImageUrl = "",
                            ListPrice = 19.0,
                            Maker = "SmoothCare",
                            Price = 14.0,
                            Price100 = 4.0,
                            Price50 = 9.0,
                            Title = "EssenceHydra"
                        },
                        new
                        {
                            Id = 89,
                            BarCode = "BC000000089",
                            CategoryId = 5,
                            Description = "A long-lasting deodorant for active days.",
                            ImageUrl = "",
                            ListPrice = 37.0,
                            Maker = "FreshShield",
                            Price = 32.0,
                            Price100 = 22.0,
                            Price50 = 27.0,
                            Title = "ZonePower"
                        },
                        new
                        {
                            Id = 90,
                            BarCode = "BC000000090",
                            CategoryId = 6,
                            Description = "A rich shaving cream for sensitive skin.",
                            ImageUrl = "",
                            ListPrice = 50.0,
                            Maker = "BladeGuard",
                            Price = 45.0,
                            Price100 = 35.0,
                            Price50 = 40.0,
                            Title = "BladeEdge"
                        },
                        new
                        {
                            Id = 91,
                            BarCode = "BC000000091",
                            CategoryId = 7,
                            Description = "Bright nail polish with lasting power.",
                            ImageUrl = "",
                            ListPrice = 36.0,
                            Maker = "ColorShine",
                            Price = 31.0,
                            Price100 = 21.0,
                            Price50 = 26.0,
                            Title = "PopColor"
                        },
                        new
                        {
                            Id = 92,
                            BarCode = "BC000000092",
                            CategoryId = 8,
                            Description = "A light perfume with floral notes.",
                            ImageUrl = "",
                            ListPrice = 60.0,
                            Maker = "EssenceMist",
                            Price = 55.0,
                            Price100 = 45.0,
                            Price50 = 50.0,
                            Title = "BloomAura"
                        },
                        new
                        {
                            Id = 93,
                            BarCode = "BC000000093",
                            CategoryId = 9,
                            Description = "A soothing balm for chapped lips.",
                            ImageUrl = "",
                            ListPrice = 30.0,
                            Maker = "LipSilk",
                            Price = 25.0,
                            Price100 = 15.0,
                            Price50 = 20.0,
                            Title = "BalmCare"
                        },
                        new
                        {
                            Id = 94,
                            BarCode = "BC000000094",
                            CategoryId = 10,
                            Description = "A cream to restore dry hands.",
                            ImageUrl = "",
                            ListPrice = 58.0,
                            Maker = "PalmSoft",
                            Price = 53.0,
                            Price100 = 43.0,
                            Price50 = 48.0,
                            Title = "CareHeal"
                        },
                        new
                        {
                            Id = 95,
                            BarCode = "BC000000095",
                            CategoryId = 11,
                            Description = "A nourishing oil for damaged hair.",
                            ImageUrl = "",
                            ListPrice = 16.0,
                            Maker = "GlowHair",
                            Price = 11.0,
                            Price100 = 1.0,
                            Price50 = 6.0,
                            Title = "DropNourish"
                        },
                        new
                        {
                            Id = 96,
                            BarCode = "BC000000096",
                            CategoryId = 12,
                            Description = "Targets dark circles and fine lines.",
                            ImageUrl = "",
                            ListPrice = 27.0,
                            Maker = "BrightEyes",
                            Price = 22.0,
                            Price100 = 12.0,
                            Price50 = 17.0,
                            Title = "LiftSoft"
                        },
                        new
                        {
                            Id = 97,
                            BarCode = "BC000000097",
                            CategoryId = 13,
                            Description = "A gentle remover for all makeup types.",
                            ImageUrl = "",
                            ListPrice = 53.0,
                            Maker = "CleanSwipe",
                            Price = 48.0,
                            Price100 = 38.0,
                            Price50 = 43.0,
                            Title = "CleanWash"
                        },
                        new
                        {
                            Id = 98,
                            BarCode = "BC000000098",
                            CategoryId = 14,
                            Description = "An organic skin lotion with no parabens.",
                            ImageUrl = "",
                            ListPrice = 63.0,
                            Maker = "BioCare",
                            Price = 58.0,
                            Price100 = 48.0,
                            Price50 = 53.0,
                            Title = "HerbalNature"
                        },
                        new
                        {
                            Id = 99,
                            BarCode = "BC000000099",
                            CategoryId = 1,
                            Description = "A revitalizing shampoo for daily use.",
                            ImageUrl = "",
                            ListPrice = 52.0,
                            Maker = "ShinyLocks",
                            Price = 47.0,
                            Price100 = 37.0,
                            Price50 = 42.0,
                            Title = "FreshSmooth"
                        },
                        new
                        {
                            Id = 100,
                            BarCode = "BC000000100",
                            CategoryId = 2,
                            Description = "A moisturizing body wash with essential oils.",
                            ImageUrl = "",
                            ListPrice = 23.0,
                            Maker = "AquaFresh",
                            Price = 18.0,
                            Price100 = 8.0,
                            Price50 = 13.0,
                            Title = "ZenWave"
                        });
                });

            modelBuilder.Entity("Beautique.Models.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReviews");
                });

            modelBuilder.Entity("Beautique.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Beautique.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("CompanyId");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("Beautique.Models.Company", b =>
                {
                    b.HasOne("Beautique.Models.Company", "company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("company");
                });

            modelBuilder.Entity("Beautique.Models.OrderDetail", b =>
                {
                    b.HasOne("Beautique.Models.OrderHeader", "OrderHeader")
                        .WithMany()
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beautique.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderHeader");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Beautique.Models.OrderHeader", b =>
                {
                    b.HasOne("Beautique.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("Beautique.Models.Product", b =>
                {
                    b.HasOne("Beautique.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Beautique.Models.ProductReview", b =>
                {
                    b.HasOne("Beautique.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beautique.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Beautique.Models.ShoppingCart", b =>
                {
                    b.HasOne("Beautique.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Beautique.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Beautique.Models.ApplicationUser", b =>
                {
                    b.HasOne("Beautique.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.Navigation("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
